### ISSUE TITLE
cong Function & trans Operator

### ISSUE THREAD

**Issue by mkohlhaas** [hesselink/type-equality#11]
Could we have something like a congruent function and an infix operator for `trans`?

```Haskell
cong ∷ a :~: b → f a :~: f b
cong Refl = Refl

(==>) :: (a :~: b) -> (b :~: c) -> a :~: c
(==>) = trans
```

Thanks for the library. Really helpful!

**Comment by phadej** [comment]
Atm `type-equality` follows the API of `base`s [`Data.Type.Equality`](https://hackage.haskell.org/package/base-4.17.0.0/docs/Data-Type-Equality.html) modules.

- `cong = apply Refl`
- `(:~:)` is also a category, so you can use `>>>` for `trans`.

**Comment by mkohlhaas** [comment]
Sweet! Thank you!
