### ISSUE TITLE
Allow base-4.20 (GHC 9.10)

### ISSUE THREAD

**Issue by andreasabel** [hesselink/type-equality#15]
> [_15] rejecting: type-equality-1 (conflict: transformers => base==4.20.0.0/installed-36c8, type-equality => base>=4.3 && <4.20)

**Comment by phadej** [comment]
I *guess* this is caused by unnecessary dependency from `constraints`: https://github.com/ekmett/constraints/pull/125

I don't think there's any reason to use `type-equality` with GHC-9.10. (e.g. `base-compat-batteries` depends on it only conditionally)
